name: Test and Build Anchor
on:
  pull_request:
  push:
    branches: ['main']
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    container:
      image: node:20-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y curl wget git build-essential pkg-config libssl-dev libudev-dev python3
      
      - name: Verify Node.js
        run: |
          node --version
      
      - name: Install pnpm
        run: |
          npm install -g pnpm@9
          pnpm --version
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
          export PATH="/root/.local/share/solana/install/active_release/bin:$PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV
          solana --version
      
      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked --force
          anchor --version
      
      - name: Generate Solana keypair
        run: |
          mkdir -p ~/.config/solana
          solana-keygen new --no-bip39-passphrase --force
      
      - name: Build Anchor project
        run: |
          pnpm run anchor build
      
      - name: Test Anchor project
        run: |
          pnpm run anchor test
